<template>
  <AdminShell active="audit" title="审计日志" subtitle="追踪管理员对用户和套餐的操作记录">
    <template #actions><button class="admin-button" :disabled="loading" @click="loadLogs"><RefreshCw :class="{'admin-spin':loading}" :size="16"/><text>刷新</text></button></template>
    <view class="admin-filter-panel audit-filters">
      <view class="admin-filter-field"><text class="admin-filter-label">管理员 ID</text><input v-model.trim="filters.admin_id" class="admin-input" type="number" placeholder="全部"/></view>
      <view class="admin-filter-field"><text class="admin-filter-label">动作</text><picker :range="actionOptions" range-key="label" :value="actionIndex" @change="changeAction"><view class="admin-select"><text>{{actionOptions[actionIndex].label}}</text><ChevronDown :size="15"/></view></picker></view>
      <view class="admin-filter-field"><text class="admin-filter-label">目标类型</text><picker :range="targetOptions" range-key="label" :value="targetIndex" @change="changeTarget"><view class="admin-select"><text>{{targetOptions[targetIndex].label}}</text><ChevronDown :size="15"/></view></picker></view>
      <view class="admin-filter-field"><text class="admin-filter-label">目标 ID</text><input v-model.trim="filters.target_id" class="admin-input" placeholder="全部"/></view>
      <view class="admin-filter-field"><text class="admin-filter-label">开始日期</text><picker mode="date" :value="filters.created_from" @change="filters.created_from=$event.detail.value"><view class="admin-select"><text>{{filters.created_from||'不限'}}</text><CalendarDays :size="15"/></view></picker></view>
      <view class="admin-filter-field"><text class="admin-filter-label">结束日期</text><picker mode="date" :value="filters.created_to" @change="filters.created_to=$event.detail.value"><view class="admin-select"><text>{{filters.created_to||'不限'}}</text><CalendarDays :size="15"/></view></picker></view>
      <button class="admin-button primary" :disabled="loading" @click="search"><Search :size="16"/><text>查询</text></button><button class="admin-button" :disabled="loading" @click="reset"><RotateCcw :size="16"/><text>重置</text></button>
    </view>
    <view class="admin-data-panel">
      <view v-if="loading" class="admin-state"><LoaderCircle class="admin-spin" :size="26"/><strong>正在读取审计日志</strong></view>
      <view v-else-if="errorMessage" class="admin-state"><AlertCircle :size="28"/><strong>审计日志加载失败</strong><text>{{errorMessage}}</text><button class="admin-button" @click="loadLogs">重新加载</button></view>
      <view v-else-if="!result.items.length" class="admin-state"><ScrollText :size="30"/><strong>暂无审计记录</strong><text>管理员执行用户或套餐变更后，记录会出现在这里。</text></view>
      <view v-else class="admin-table-scroll"><view class="admin-table audit-table">
        <view class="admin-table-row header"><view class="admin-table-cell">管理员</view><view class="admin-table-cell">动作</view><view class="admin-table-cell">目标</view><view class="admin-table-cell">原因</view><view class="admin-table-cell">时间</view><view class="admin-table-cell"></view></view>
        <view v-for="item in result.items" :key="item.id" class="admin-table-row"><view class="admin-table-cell" data-label="管理员"><view><strong>{{item.admin_username}}</strong><small>{{item.admin_email}} · ID {{item.admin_id}}</small></view></view><view class="admin-table-cell" data-label="动作"><text class="action-code">{{actionLabel(item.action)}}</text></view><view class="admin-table-cell" data-label="目标"><view><strong>{{targetLabel(item.target_type)}}</strong><small>ID {{item.target_id||'--'}}</small></view></view><view class="admin-table-cell reason-cell" data-label="原因"><text>{{item.reason||'--'}}</text></view><view class="admin-table-cell" data-label="时间"><text>{{formatDateTime(item.created_at)}}</text></view><view class="admin-table-cell admin-table-actions" data-label="操作"><button class="admin-link-button" @click="openChanges(item)"><Braces :size="15"/><text>查看变更</text></button></view></view>
      </view></view>
      <AdminPagination :page="result.page" :page-size="result.page_size" :total="result.total" :loading="loading" @change="changePage"/>
    </view>

    <AdminModal :open="Boolean(selectedLog)" title="审计变更" :subtitle="selectedLog?`${actionLabel(selectedLog.action)} · ${formatDateTime(selectedLog.created_at)}`:''" width="620px" @close="selectedLog=null">
      <view v-if="selectedLog" class="audit-detail">
        <view class="audit-meta"><view><text>管理员</text><text>{{selectedLog.admin_username}}（ID {{selectedLog.admin_id}}）</text></view><view><text>操作目标</text><text>{{targetLabel(selectedLog.target_type)}} · {{selectedLog.target_id||'--'}}</text></view><view><text>操作原因</text><text>{{selectedLog.reason||'--'}}</text></view></view>
        <view v-if="hasSnapshots" class="change-columns"><view><text>修改前</text><view v-for="entry in objectEntries(selectedLog.changes.before)" :key="entry[0]"><text>{{fieldLabel(entry[0])}}</text><text>{{displayValue(entry[1])}}</text></view></view><ArrowRight :size="18"/><view><text>修改后</text><view v-for="entry in objectEntries(selectedLog.changes.after)" :key="entry[0]"><text>{{fieldLabel(entry[0])}}</text><text>{{displayValue(entry[1])}}</text></view></view></view>
        <view v-else class="raw-change"><text>变更内容</text><text>{{safeJson(selectedLog.changes)}}</text></view>
      </view>
      <template #footer><button class="admin-button" @click="selectedLog=null">关闭</button></template>
    </AdminModal>
  </AdminShell>
</template>

<script setup>
import { computed, reactive, ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import { AlertCircle, ArrowRight, Braces, CalendarDays, ChevronDown, LoaderCircle, RefreshCw, RotateCcw, ScrollText, Search } from '@lucide/vue'
import AdminModal from '../../components/admin/AdminModal.vue';import AdminPagination from '../../components/admin/AdminPagination.vue';import AdminShell from '../../components/admin/AdminShell.vue';import { adminApi } from '../../api';import { useAdminStore } from '../../stores/admin';import { formatDateTime,normalizeInteger,requireAdminPage } from '../../utils/admin'
const adminStore=useAdminStore();const loading=ref(true);const errorMessage=ref('');const filters=reactive({admin_id:'',action:null,target_type:null,target_id:'',created_from:'',created_to:''});const actionIndex=ref(0);const targetIndex=ref(0);const selectedLog=ref(null);const result=reactive({items:[],total:0,page:1,page_size:20})
const actionOptions=[{label:'全部动作',value:null},{label:'用户状态变更',value:'user.status_update'},{label:'用户次数调整',value:'user.credit_adjust'},{label:'创建套餐',value:'package.create'},{label:'修改套餐',value:'package.update'}];const targetOptions=[{label:'全部目标',value:null},{label:'用户',value:'user'},{label:'用户次数',value:'user_credit'},{label:'套餐',value:'package'}]
const hasSnapshots=computed(()=>selectedLog.value?.changes&&typeof selectedLog.value.changes.before==='object'&&typeof selectedLog.value.changes.after==='object')
onShow(async()=>{if(await requireAdminPage(adminStore))await loadLogs()})
async function loadLogs(){const adminId=filters.admin_id===''?null:normalizeInteger(filters.admin_id);if(filters.admin_id!==''&&(adminId===null||adminId<1)){errorMessage.value='管理员 ID 需要是正整数';return}loading.value=true;errorMessage.value='';try{Object.assign(result,await adminApi.auditLogs({admin_id:adminId,action:filters.action,target_type:filters.target_type,target_id:filters.target_id,created_from:filters.created_from?`${filters.created_from}T00:00:00`:null,created_to:filters.created_to?`${filters.created_to}T23:59:59`:null,page:result.page,page_size:result.page_size}))}catch(error){errorMessage.value=error.message}finally{loading.value=false}}
function search(){if(filters.created_from&&filters.created_to&&filters.created_from>filters.created_to){errorMessage.value='开始日期不能晚于结束日期';return}result.page=1;loadLogs()}function reset(){Object.assign(filters,{admin_id:'',action:null,target_type:null,target_id:'',created_from:'',created_to:''});actionIndex.value=0;targetIndex.value=0;result.page=1;loadLogs()}function changeAction(event){actionIndex.value=Number(event.detail.value);filters.action=actionOptions[actionIndex.value].value}function changeTarget(event){targetIndex.value=Number(event.detail.value);filters.target_type=targetOptions[targetIndex.value].value}function changePage(page){result.page=page;loadLogs()}function openChanges(item){selectedLog.value=item}
function actionLabel(value){return actionOptions.find(item=>item.value===value)?.label||value}function targetLabel(value){return targetOptions.find(item=>item.value===value)?.label||value}function fieldLabel(value){return {is_active:'启用状态',balance:'余额',name:'套餐名称',price:'价格',credit_count:'包含次数',change_count:'变更次数'}[value]||value}function objectEntries(value){return value&&typeof value==='object'?Object.entries(value):[]}function displayValue(value){if(value===true)return'是';if(value===false)return'否';if(value===null||value===undefined)return'--';if(typeof value==='object')return safeJson(value);return String(value)}function safeJson(value){try{return JSON.stringify(value??{},null,2)}catch(_){return String(value)}}
</script>

<style scoped>
.audit-filters{display:grid;grid-template-columns:110px 165px 145px 110px 140px 140px 80px 80px;align-items:end}.audit-filters>.admin-button{width:80px;min-width:80px}.audit-table{min-width:1040px}.audit-table .admin-table-row{grid-template-columns:1.45fr 1.15fr .9fr 1.4fr 1.1fr .8fr}.action-code{display:inline-flex;min-height:24px;align-items:center;border-radius:5px;background:#edf5f2;padding:4px 8px;color:#276754;font-size:11px;font-weight:650}.reason-cell text{display:-webkit-box;overflow:hidden;-webkit-box-orient:vertical;-webkit-line-clamp:2}.audit-meta{display:grid;grid-template-columns:1fr 1fr;gap:14px;border:1px solid #e1e6e3;border-radius:7px;background:#f8faf9;padding:15px}.audit-meta>view:last-child{grid-column:1/-1}.audit-meta text:first-child{display:block;color:#7a8680;font-size:11px}.audit-meta text:last-child{display:block;margin-top:5px;color:#2b3731;font-size:12px;line-height:1.5}.change-columns{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:13px;margin-top:16px}.change-columns>view{align-self:stretch;border:1px solid #e1e6e3;border-radius:7px;padding:14px}.change-columns>view>text:first-child{display:block;margin-bottom:10px;color:#26322d;font-size:13px;font-weight:700}.change-columns>view>view{display:flex;justify-content:space-between;gap:12px;border-top:1px solid #edf0ee;padding:8px 0;font-size:11px}.change-columns>view>view text:first-child{color:#79857f}.change-columns>view>view text:last-child{overflow-wrap:anywhere;color:#29352f;text-align:right}.raw-change{margin-top:16px}.raw-change>text:first-child{display:block;margin-bottom:8px;color:#26322d;font-size:13px;font-weight:700}.raw-change>text:last-child{display:block;overflow-x:auto;border:1px solid #e1e6e3;border-radius:7px;background:#f7f9f8;padding:14px;color:#415049;font-family:Consolas,monospace;font-size:11px;line-height:1.6;white-space:pre-wrap}@media(max-width:1180px){.audit-filters{grid-template-columns:repeat(4,minmax(0,1fr))}.audit-filters>.admin-button{width:100%}}@media(max-width:760px){.audit-filters{grid-template-columns:1fr 1fr}.audit-table{min-width:0}.change-columns{grid-template-columns:1fr}.change-columns>svg{margin:auto;transform:rotate(90deg)}}@media(max-width:420px){.audit-filters{grid-template-columns:1fr}.audit-meta{grid-template-columns:1fr}.audit-meta>view:last-child{grid-column:auto}}
</style>
