"""v1

Revision ID: 052eb03d621c
Revises: 
Create Date: 2026-07-20 17:12:14.586147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '052eb03d621c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('_password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    op.create_table('credit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('change_count', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=200), nullable=False),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_credit_log_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_log'))
    )
    op.create_index(op.f('ix_credit_log_user_id'), 'credit_log', ['user_id'], unique=False)
    op.create_table('user_credit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('total_used', sa.Integer(), nullable=False),
    sa.Column('total_recharged', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_credit_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_credit'))
    )
    op.create_index(op.f('ix_user_credit_user_id'), 'user_credit', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_credit_user_id'), table_name='user_credit')
    op.drop_table('user_credit')
    op.drop_index(op.f('ix_credit_log_user_id'), table_name='credit_log')
    op.drop_table('credit_log')
    op.drop_table('user')
    # ### end Alembic commands ###
