"""add package and user order tables

Revision ID: 12657eb5b2af
Revises: 052eb03d621c
Create Date: 2026-07-22 15:01:49.936271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12657eb5b2af'
down_revision: Union[str, None] = '052eb03d621c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('credit_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package')),
    sa.UniqueConstraint('name', name=op.f('uq_package_name'))
    )
    op.create_table('user_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('credit_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('alipay_trade_no', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], name=op.f('fk_user_order_package_id_package')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_order_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_order'))
    )
    op.create_index(op.f('ix_user_order_order_no'), 'user_order', ['order_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_order_order_no'), table_name='user_order')
    op.drop_table('user_order')
    op.drop_table('package')
    # ### end Alembic commands ###
